apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: callowayart
      tier: frontend
      type: deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: callowayart
        tier: frontend
        type: deployment
    spec:
      containers:
      - name: frontend
        image: callowaylc/callowayart
        env:
          - name: GET_HOSTS_FROM
            value: dns
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress
            MIGRATION_AWS_ACCESS_KEY_ID: ${MIGRATION_AWS_ACCESS_KEY_ID}
            MIGRATION_AWS_SECRET_ACCESS_KEY: ${MIGRATION_AWS_SECRET_ACCESS_KEY}
        ports:
        - containerPort: 80