apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: callowayart
      tier: frontend
      type: deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: callowayart
    spec:
      containers:
      - name: frontend
        image: callowaylc/callowayart
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80