apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: callowayart
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: callowayart
    tier: frontend
